# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    # http://symfony.com/doc/current/reference/dic_tags.html
    app.subscriber.visit.events:
        class: AppBundle\Subscriber\VisitEventsSubscriber
        tags:
            - { name: kernel.event_subscriber }

    admin.subscriber.category.form:
        class: AdminBundle\Subscriber\CategoryFormSubscriber
        tags:
          - { name: kernel.event_subscriber}

    admin.subscriber.kernel.events:
          class: AdminBundle\Subscriber\KernelEventsSubscriber
          arguments: ['@twig', '@session' ] # Permet d'utiliser le service Twig le nom du service est twig_environnment
          tags:
            - { name: kernel.event_subscriber}


    admin.twig.extension:
        class: AdminBundle\Twig\AppExtension
        arguments: [ '@doctrine', '@twig' ]
        tags:
          - { name: twig.extension}


    admin.service.utils.string:
        class: AdminBundle\Service\Utils\StringService

    admin.service.upload:
        class: AdminBundle\Service\UploadService
        arguments: [ '@admin.service.utils.string', '%upload_dir%' ]

    admin.service.unlink:
        class: AdminBundle\Service\UnlinkService
        arguments: [ '%upload_dir%' ]

    admin.listener.product:
        class: AdminBundle\Listener\ProductListener
        arguments: [ '@admin.service.upload', '@admin.service.unlink', '%default_img_declare%' ]
        tags:
            - { name: doctrine.orm.entity_listener }

    admin.service.utils.token:
        class: AdminBundle\Service\Utils\TokenService

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
          - { name: twig.extension}
