<?php

namespace AdminBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindCommentsByProduct($product_id) {
        $results = $this
            ->createQueryBuilder('c')
            ->where('c.product = :idProduct')
            ->setParameters(['idProduct' => $product_id])
            ->getQuery()
            ->getResult();
        return $results;
    }

    public function FindAvgCommentProduct($product_id) {
        $results = $this
            ->createQueryBuilder('c')
            ->select('AVG(c.score)')
            ->where('c.product = :idProduct')
            ->setParameters(['idProduct' => $product_id])
            ->getQuery()
            ->getSingleScalarResult();
        return $results;
    }




}
