<?php
/**
 * Created by PhpStorm.
 * User: wamobi8
 * Date: 26/01/17
 * Time: 11:55
 */

namespace AppBundle\Command;


use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class UserAddRoleCommand extends ContainerAwareCommand
{
    // clic droit->generate->puis Override Methods 'selectionnner les methodes : configure et execute'
    protected function configure()
    {
      // parent::configure(); // TODO: Change the autogenerated stub
        $this
            ->setName('app:user:role:add')
            ->setDescription('Add role to an user')
            ->addArgument('username', InputArgument::REQUIRED,'Define username')
            ->addArgument('role', InputArgument::REQUIRED,'Define role')
            ;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        //parent::execute($input, $output); // TODO: Change the autogenerated stub

        $username =  $input->getArgument('username');
        $role = $input->getArgument('role');

        $container = $this->getContainer();
        $doctrine = $container->get('doctrine');
        $em = $doctrine->getManager();

        $rcUser = $doctrine->getRepository('AdminBundle:User')->findOneBy([
            'username'=>$username
        ]);

        $rcRole = $doctrine->getRepository('AdminBundle:Role')->findOneBy([
            'name' => 'ROLE_'.strtoupper($role)
        ]);

        $rcUser->addRole($rcRole);
        $em->persist($rcUser);
        $em->flush();


        $output->writeln(" $username // $role");

    }
}